Update README formatting and content
ARMmbed/mbed-os-example-blockdevice pull request #64
Opened 2021-01-18 12:01 UTC by harmut01

## Summary 
Updated template following format used in mbed-os-example-blinky and fixed explanations to align with code (i.e. SDBlockDevice used by default not SPIFBLockDevice). Removed linker table and deprecated compilers. Checked that output in README matches output from source

2021-01-29 15:43 UTC, evedon requested changes

2021-01-29 15:43 UTC, evedon commented on README.md
> +The example project is part of the [Arm Mbed OS Official Examples](https://os.mbed.com/code/). It contains an application that demonstrates how to use a block device as storage on supported [Mbed boa
It's not necessary to link all official examples, we only do it for blinnky which is the "get started" example. In addition the first sentence (copied from blinky) is not the best! 
```suggestion
This example shows how to use a block device as storage on supported [Mbed boards](https://os.mbed.com/platforms/).
```

2021-01-29 15:43 UTC, evedon commented on README.md
> +1. Change the current directory to where the project was imported: `cd mbed-os-example-blockdevice`
The next two lines were part of a table of contents and should be removed as they do not flow with this section on how to import the example.

2021-01-29 15:43 UTC, evedon commented on README.md
> +1. Run the following command to build the example project and program the microcontroller flash memory:
```suggestion
1. Run the following command to build the example project, program the microcontroller flash memory , and open a serial terminal:
```

2021-01-29 15:43 UTC, evedon commented on README.md
> +    mbed compile -m <TARGET> -t <TOOLCHAIN> --flash
```suggestion
    mbed compile -m <TARGET> -t <TOOLCHAIN> --flash --sterm
```

2021-01-29 15:43 UTC, evedon commented on README.md
> +Your PC may take a few minutes to compile your code.
Let's remove this sentence.

2021-01-29 15:43 UTC, evedon commented on README.md
> +Depending on the target, you can build the example project with the `GCC_ARM`, or `ARM` toolchain. Run the command below to determine which toolchain supports your target:
```suggestion
Depending on the target, you can build the example project with different toolchains. Run the command below to determine which toolchain supports your target:
```

2021-01-29 15:43 UTC, evedon commented on README.md
> +Once you have programmed your board, open the UART of the board in your preferred UART viewing program. To launch the serial console provided by Mbed, run the command `mbedtools sterm`. If you don't
It's simpler to use with `mbed compile`

2021-01-29 15:43 UTC, evedon commented on README.md
> +If you see garbled text from the read operations check that your SD card is securely fixed in the port. If there's no SD card mounted the application returns garbage characters.
This should be in the `Troubleshooting` section

2021-02-01 09:39 UTC, harmut01 commented
@evedon thanks for you feedback! I have added a new commit that should address your comments.

2021-02-02 09:22 UTC, evedon approved these changes
Looks good.

2021-02-02 09:22 UTC, merged