Fix and simplify BlockDevice selection
ARMmbed/mbed-os-example-blockdevice pull request #75
Opened 2021-08-03 15:20 UTC by LDong-Arm

This example goes through possible types of block devices one by one, and it has several issues:
* If a target has multiple block devices, the last one checked is used rather than the default instance defined by Mbed OS.
* A check for FlashIAP is missing, making this example fail to compile on several FlashIAP targets. This just reflects the impracticality of maintaining a hardcoded list.
* The header HeapBlockDevice.h is included but not actually used, so a fallback option is lacking for targets without a hardware block device.

To solve the above and simplify this example,
* Use the static member function `BlockDevice::get_default_instance()` to get the default block device, then use `BlockDevice::get_type()` to let users know the actual type.
* If no default block device is available, create a HeapBlockDevice instance to continue this example.

2021-08-03 15:21 UTC, LDong-Arm commented
@ARMmbed/mbed-os-core I created this while using this example to work on https://github.com/ARMmbed/mbed-os/issues/12574

2021-08-03 15:52 UTC, Patater requested changes

2021-08-03 15:52 UTC, Patater commented on main.cpp
> +    printf("bd->init -> %d\n", err);
We are changing a lot of print statements. Do we also need to update the expected log file?

https://github.com/ARMmbed/mbed-os-example-blockdevice/blob/master/tests/blockdevice.log

2021-08-03 15:55 UTC, Patater requested changes

2021-08-03 15:55 UTC, Patater commented on main.cpp
> +        bd = &heap_bd;
`heap_bd` goes out of scope after this block ends, so your pointer becomes invalid.

2021-08-03 16:53 UTC, LDong-Arm reviewed
@Patater Thanks, very good catches! Now fixed.

2021-08-03 16:54 UTC, LDong-Arm commented
Log tested with
```
mbedhtrun --skip-flashing --compare-log tests/blockdevice.log -p /dev/tty.usbmodem141102 --sync 0
```

2021-08-04 08:36 UTC, Patater approved these changes
LGTM

2021-08-04 08:38 UTC, Patater commented on main.cpp
> +        printf("No hardware BlockDevice found, using heap\n");
We don't need this in the log because unmatched lines are essentially skipped.

2021-08-04 15:43 UTC, merged